export const ADD_COMPLAINS = 'ADD_COMPLAINS';
export const LOAD_COMPLAINS_LOADING = 'LOAD_COMPLAINS_LOADING';
export const LOAD_COMPLAINS_ERROR = 'LOAD_COMPLAINS_ERROR';

export const POST_COMPLAIN_SUCCESS = 'POST_COMPLAIN_SUCCESS';
export const POST_COMPLAIN_FAILURE = 'POST_COMPLAIN_FAILURE';

export const COMPLAIN_STATUS_CHANGE_SUCCESS = 'COMPLAIN_STATUS_CHANGE_SUCCESS';
export const COMPLAIN_STATUS_CHANGE_FAILURE = 'COMPLAIN_STATUS_CHANGE_FAILURE';